/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.AdministratorController;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Discipline;
import model.Person;

/**
 *
 * @author chejo
 */
public class AddAlumn extends javax.swing.JFrame {

    
    private final AdministratorController controller = new AdministratorController();
    
    private DefaultComboBoxModel modelTrainers = new DefaultComboBoxModel<>();
    private DefaultComboBoxModel modelDisciplines = new DefaultComboBoxModel<>();
    private DefaultComboBoxModel modelHours = new DefaultComboBoxModel<>();
    /**
     * Creates new form AddAlumn
     */
    public AddAlumn() {
        initComponents();
        loadTrainers();
        loadDisciplines();
        loadHours();
    }
    
    private void loadTrainers() {
        ArrayList<Person> trainers = controller.getAllTrainersForDiscipline();
        for (Person trainer : trainers) {
            modelTrainers.addElement(trainer.getName() + " " + trainer.getLastname());
        }
        comboBoxTrainer.setModel(modelTrainers);
    }

    private void loadDisciplines() {
        ArrayList<Discipline> disciplines = controller.getAllDisciplines();
        for (Discipline discipline : disciplines) {
            modelDisciplines.addElement(discipline.getName());
        }
        comboBoxDiscipline.setModel(modelDisciplines);
    }
    
    private void loadHours() {
        modelHours.addElement("8:00 - 9:00");
        modelHours.addElement("9:00 - 10:00");
        modelHours.addElement("10:00 - 11:00");
        modelHours.addElement("11:00 - 13:00");
        modelHours.addElement("12:00 - 13:00");
        modelHours.addElement("13:00 - 14:00");
        modelHours.addElement("14:00 - 15:00");
        modelHours.addElement("15:00 - 16:00");
        modelHours.addElement("16:00 - 17:00");
        modelHours.addElement("17:00 - 18:00");
        modelHours.addElement("18:00 - 19:00");
        modelHours.addElement("19:00 - 20:00");
        modelHours.addElement("20:00 - 19:00");
        modelHours.addElement("21:00 - 22:00");
        comboBoxHours.setModel(modelHours);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        InputNameAlumn = new javax.swing.JTextField();
        InputLastNameAlumn = new javax.swing.JTextField();
        InputDniAlumn = new javax.swing.JTextField();
        InputEmailAlumn = new javax.swing.JTextField();
        InputPasswordAlumn = new javax.swing.JTextField();
        comboBoxDiscipline = new javax.swing.JComboBox<>();
        comboBoxTrainer = new javax.swing.JComboBox<>();
        AddAlumn = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Horas = new javax.swing.JLabel();
        comboBoxHours = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InputNameAlumn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNameAlumnActionPerformed(evt);
            }
        });

        comboBoxDiscipline.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboBoxTrainer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        AddAlumn.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        AddAlumn.setLabel("Agregar");
        AddAlumn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddAlumnMouseClicked(evt);
            }
        });
        AddAlumn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAlumnActionPerformed(evt);
            }
        });

        jLabel1.setText("NOMBRES :");

        jLabel2.setText("APELLIDOS :");

        jLabel3.setText("DNI");

        jLabel4.setText("EMAIL :");

        jLabel5.setText("CONTRASEÑA");

        jLabel6.setText("DISCIPLINA");

        jLabel7.setText("PROFESOR");

        Horas.setText("Horas");

        comboBoxHours.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(AddAlumn, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Horas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(InputNameAlumn)
                    .addComponent(InputLastNameAlumn)
                    .addComponent(InputDniAlumn)
                    .addComponent(InputEmailAlumn)
                    .addComponent(InputPasswordAlumn)
                    .addComponent(comboBoxDiscipline, 0, 236, Short.MAX_VALUE)
                    .addComponent(comboBoxTrainer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboBoxHours, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(75, 75, 75))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputNameAlumn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputLastNameAlumn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputDniAlumn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputEmailAlumn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputPasswordAlumn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxDiscipline, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxTrainer, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Horas)
                        .addGap(44, 44, 44))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(comboBoxHours, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)))
                .addComponent(AddAlumn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputNameAlumnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNameAlumnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputNameAlumnActionPerformed

    private void AddAlumnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAlumnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddAlumnActionPerformed

    private void AddAlumnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddAlumnMouseClicked
        String name = InputNameAlumn.getText();
        String lastname = InputLastNameAlumn.getText();
        String dni = InputDniAlumn.getText();
        String email = InputEmailAlumn.getText();
        String password = InputPasswordAlumn.getText();                                 
        int trainer_id = comboBoxTrainer.getSelectedIndex() + 1;
        int discipline_id = comboBoxDiscipline.getSelectedIndex() + 1;
        String hours = (String) comboBoxHours.getSelectedItem();

        if (name.isBlank() && lastname.isBlank() && email.isBlank() && password.isBlank() && dni.isBlank()) { //Blank sirve para validar si tiene espacios y si es vacio
            JOptionPane.showMessageDialog(null, "No se completó todos los campos");
        } else {
            try {
                Person student = new Person(-1, name, lastname, email, password, dni, discipline_id, trainer_id, hours);
                boolean response = controller.createStudent(student);
                if (response == true) {
                    this.dispose(); // Cerrar el JFrame
                    JOptionPane.showMessageDialog(null, "El alumno fue creado correctamente");
                } else {
                    JOptionPane.showMessageDialog(null, "El alumno no pudo crearse");
                }
            } catch (Exception e) {
                System.out.print("Error, no se pudo crear el profesor");
                System.out.print(e.getMessage());
            }
        }
    }//GEN-LAST:event_AddAlumnMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button AddAlumn;
    private javax.swing.JLabel Horas;
    private javax.swing.JTextField InputDniAlumn;
    private javax.swing.JTextField InputEmailAlumn;
    private javax.swing.JTextField InputLastNameAlumn;
    private javax.swing.JTextField InputNameAlumn;
    private javax.swing.JTextField InputPasswordAlumn;
    private javax.swing.JComboBox<String> comboBoxDiscipline;
    private javax.swing.JComboBox<String> comboBoxHours;
    private javax.swing.JComboBox<String> comboBoxTrainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
