/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author chejo
 */
public class InicioTrainer extends javax.swing.JFrame {

    private ImageIcon imagen;
    private Icon icono;

    /**
     * Creates new form InicioTrainer
     */
    public InicioTrainer() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.PintarImagen(this.Panel1, "src/img/fondo.jpg");
    }

    private void PintarImagen(JLabel Panel1, String ruta) {
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(
                Panel1.getWidth(),
                Panel1.getHeight(),
                Image.SCALE_DEFAULT)
        );
        Panel1.setIcon(this.icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        buttonStudentsTrainer = new java.awt.Button();
        ButtonReadComments = new java.awt.Button();
        Panel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Wide Latin", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("HELLO TRAINER !");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 580, 116));

        buttonStudentsTrainer.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Yellow"));
        buttonStudentsTrainer.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 36)); // NOI18N
        buttonStudentsTrainer.setForeground(new java.awt.Color(255, 0, 0));
        buttonStudentsTrainer.setLabel("Students");
        buttonStudentsTrainer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonStudentsTrainerMouseClicked(evt);
            }
        });
        buttonStudentsTrainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStudentsTrainerActionPerformed(evt);
            }
        });
        jPanel1.add(buttonStudentsTrainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 216, 89));

        ButtonReadComments.setBackground(new java.awt.Color(255, 153, 0));
        ButtonReadComments.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonReadComments.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 24)); // NOI18N
        ButtonReadComments.setForeground(new java.awt.Color(255, 0, 0));
        ButtonReadComments.setLabel("COMMENTS STUDENTS");
        ButtonReadComments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonReadCommentsMouseClicked(evt);
            }
        });
        ButtonReadComments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonReadCommentsActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonReadComments, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 250, 104));
        jPanel1.add(Panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 680, 646));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonStudentsTrainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStudentsTrainerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonStudentsTrainerActionPerformed

    private void buttonStudentsTrainerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonStudentsTrainerMouseClicked
        AlumnTrainer alumnTrainer = new AlumnTrainer();
        alumnTrainer.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE); //Esto hara que al cerrar el JFrame, se oculte en lufar de terminar la ejecucion del programa
        alumnTrainer.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_buttonStudentsTrainerMouseClicked

    private void ButtonReadCommentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonReadCommentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonReadCommentsActionPerformed

    private void ButtonReadCommentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonReadCommentsMouseClicked
        ReadComments comments = new ReadComments();
        comments.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE); //Esto hara que al cerrar el JFrame, se oculte en lufar de terminar la ejecucion del programa
        comments.setVisible(true);
    }//GEN-LAST:event_ButtonReadCommentsMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button ButtonReadComments;
    private javax.swing.JLabel Panel1;
    private java.awt.Button buttonStudentsTrainer;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
